name: C Build and Test

on:
  workflow_dispatch:
    inputs:
      prerelease:
        type: boolean
        description: "Mark this as a pre-release?"
        default: false
  # push:
  #   branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the C program
        run: gcc -std=c17 -O2 -Wall -Wextra -Werror -o main main.c

      - name: Run the program
        run: ./main

      - name: Upload to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "main,products.csv"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.run_number }}
          name: "Release ${{ github.run_number }}"
          body: "Automated release of the C program"
          draft: false
          prerelease: ${{ inputs.prerelease }}
